module.exports = {
	OPEN_ABOUT: 'OPEN_ABOUT',
	OPEN_CONTACT: 'OPEN_CONTACT',
	GET_SUB_FROM_FLICKR: 'GET_SUB_FROM_FLICKR',
	SET_CURRENT_WORK: 'SET_CURRENT_WORK',
	SET_PROJECTS: 'SET_PROJECTS',
	ROUTE: {
    	TRANSITION: "ROUTE:TRANSITION"
  	}
};